site_name: Aulas de Versionamento de Código e Sistemas de Mensageria
site_description: Site de aulas e materiais didáticos da matéria "Versionamento de Código e Sistemas de Mensageria"
site_author: Luccas Alencar

# Repositório (substitua pelo seu)
repo_name: LuccasAlencar/aulas-versionamento-de-codigo-e-sistemas-de-mensageria
repo_url: https://github.com/LuccasAlencar/aulas-versionamento-de-codigo-e-sistemas-de-mensageria

# Tema
theme:
  name: material
  language: pt-BR
  palette:
    # Modo claro
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Modo escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer

# Plugins
plugins:
  - search:
      lang: pt

# Extensões Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Navegação
nav:
  - Home: index.md
  - Aulas:
    - Aula 1 – O que é Versionamento de Código? : aulas/aula1.md
    - Aula 2 – Por que versionar um código? : aulas/aula2.md
    - Aula 3 – Conceitos de repositório e histórico : aulas/aula3.md
    - Aula 4 - Visão geral das ferramentas de versionamento: aulas/aula4.md
    - Aula 5 - Comparando ferramentas: aulas/aula5.md
    - Aula 6 - Repositórios públicos vs privados: aulas/aula6.md


extra:
  generator: false